"""Helpers for building admissions-ready demo reports."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from adoif.db import ExtractionRecord
from adoif.models import StoredArtifact
from adoif.services.notes import Note
from adoif.services.schedule import ScheduleEntry


@dataclass(slots=True)
class ScreeningSnapshot:
    name: str
    included: int
    excluded: int
    pending: int


@dataclass(slots=True)
class ReportData:
    artifacts: Sequence[StoredArtifact]
    screening: Sequence[ScreeningSnapshot]
    extractions: Sequence[ExtractionRecord]
    notes: Sequence[Note]
    schedule: Sequence[ScheduleEntry]


def build_demo_report(data: ReportData) -> str:
    lines: list[str] = []
    lines.append("# ADOIF Demo Report")
    lines.append("")
    lines.append("_Generated by `adoif demo-report`. All data stays local; no PHI/PII is stored._")
    lines.append("")

    lines.append("## Library Snapshot")
    total = len(data.artifacts)
    pdfs = sum(1 for artifact in data.artifacts if artifact.pdf_path)
    lines.append(f"- Total articles: {total}")
    lines.append(f"- PDFs available: {pdfs}")
    if data.artifacts:
        lines.append("- Representative articles:   ")
        for artifact in data.artifacts[:5]:
            tags = ", ".join(artifact.metadata.tags) or "no tags"
            lines.append(
                f"  - {artifact.metadata.title} ({artifact.metadata.doi}) — {artifact.metadata.journal or 'journal tbd'} — tags: {tags}"
            )
    else:
        lines.append("- Representative articles: library not populated yet.")
    lines.append("")

    if data.screening:
        lines.append("## Screening Progress")
        for snap in data.screening:
            lines.append(
                f"- {snap.name}: included {snap.included}, excluded {snap.excluded}, pending {snap.pending}"
            )
        lines.append("")

    if data.extractions:
        lines.append("## Extraction Highlights")
        for record in data.extractions[:5]:
            lines.append(
                f"- {record.doi}: status {record.status} — outcomes {record.outcomes_summary or 'tbd'}"
            )
        lines.append("")

    if data.notes:
        lines.append("## Notes & Reflections")
        for note in data.notes[:5]:
            tag_text = ", ".join(note.tags) or "no tags"
            lines.append(
                f"- {note.created_at.strftime('%Y-%m-%d')} [{tag_text}] {note.doi}: {note.body}"
            )
        lines.append("")

    if data.schedule:
        lines.append("## Upcoming Readings")
        for entry in data.schedule[:5]:
            lines.append(
                f"- {entry.due_date.strftime('%Y-%m-%d')} – {entry.course}: {entry.title} ({entry.doi or 'doi pending'})"
            )
        lines.append("")

    lines.append("## Screenshot Placeholders")
    lines.append("![Library Screenshot](TODO-library.png)")
    lines.append("![Dashboard Notes](TODO-dashboard.png)")
    lines.append("")
    lines.append("Security: ADOIF keeps everything in your `ADOIF_DATA_DIR`. Only synthetic or student-owned data appears in this report.")
    lines.append("")
    lines.append("Next steps: swap in real screenshots, attach the generated Markdown to your admissions packet, and mention your local-first research workflow.")

    return "\n".join(lines)
